<?php

/**
 * Build-time Identity Capture Script
 *
 * This script runs during `composer install` (via post-install-cmd) while
 * the .git directory still exists. It captures the GitHub username from
 * the git remote origin URL and writes it to a cached file for runtime use.
 *
 * Supported URL formats:
 * - git@github.com:USERNAME/repo.git
 * - https://github.com/USERNAME/repo.git
 * - https://github.com/USERNAME/repo
 */

// Only run if .git directory exists (build-time, not runtime)
if (! is_dir('.git')) {
    exit(0);
}

// Get the remote origin URL
$remote = trim(shell_exec('git config --get remote.origin.url') ?? '');
if (! $remote) {
    exit(0);
}

// Parse username from git URL
// Matches: git@github.com:USER/repo.git OR https://github.com/USER/repo.git
if (preg_match('#[:/]([^/]+)/[^/]+(\.git)?$#', $remote, $matches)) {
    $username = $matches[1];

    // Skip if it's the original template repo
    if ($username === 'laravel') {
        exit(0);
    }

    // Ensure bootstrap/cache directory exists
    if (! is_dir('bootstrap/cache')) {
        mkdir('bootstrap/cache', 0755, true);
    }

    // Write to a cached PHP file that will be included at runtime
    // This persists through Laravel Cloud deployments unlike .env modifications
    $cacheFile = 'bootstrap/cache/github-identity.php';
    $content = sprintf(
        "<?php\n\n// Auto-generated by scripts/capture-identity.php during build\nreturn %s;\n",
        var_export($username, true)
    );

    file_put_contents($cacheFile, $content);

    echo "Captured GitHub identity: {$username}\n";
}
